### ISSUE TITLE
沈没した船の先端のラベル表示がズレている

### ISSUE THREAD

**Issue by michael-ilcsy** [michael-ilcsy/elm-battleship#1]
ヒット時及び沈没時の胴体部分の表示はラベルが真ん中に表示されているが、沈没時のセンタのラベル表示がズレているので修正する

以下の場所を再現したいtypeに変えることで再現可能
https://github.com/michael-ilcsy/elm-battleship/blob/master/src/Main.elm#L120

`Array.repeat gameBoardSize <| Array.repeat gameBoardSize <| Sunk B <| Body`
`Array.repeat gameBoardSize <| Array.repeat gameBoardSize <| Sunk B <| Tip Right`

<img width="354" alt="スクリーンショット 2020-07-28 21 22 25" src="https://user-images.githubusercontent.com/46617731/88664887-b687e100-d118-11ea-9412-80d958fbd455.png">
<img width="353" alt="スクリーンショット 2020-07-28 21 22 11" src="https://user-images.githubusercontent.com/46617731/88664903-bc7dc200-d118-11ea-8666-86724c870af0.png">

**Comment by diggymo** [comment]
スクショ

<img width="404" alt="スクリーンショット 2020-08-02 15 33 25" src="https://user-images.githubusercontent.com/24623083/89117047-86a05b00-d4d5-11ea-82bd-e4f61909442f.png">

<img width="363" alt="スクリーンショット 2020-08-02 15 33 15" src="https://user-images.githubusercontent.com/24623083/89117056-9b7cee80-d4d5-11ea-8069-df7e0279c626.png">
